use sakila;

#1 List the number of films per category.
select category_id, count(f.film_id) AS number_films
from film f
JOIN film_category fc
ON  f.film_id = fc.film_id
GROUP BY category_id ;

#2 Retrieve the store ID, city, and country for each store.
select store_id, city , country
from store s
JOIN address a
ON a.address_id = s.address_id
JOIN city ci
ON ci.city_id = a.city_id
JOIN country co
ON co.country_id = co.country_id;

#3 Calculate the total revenue generated by each store in dollars.
select s.store_id, SUM(amount) AS total_revenue
from customer c
JOIN payment p
ON c.customer_id = p.customer_id
JOIN store s
ON c.store_id = s.store_id
GROUP BY store_id;

#4 Determine the average running time of films for each category.
select C.category_id , C.name, AVG(length) AS average_running_time_by_category
from film F
JOIN film_category FC
ON F.film_id = FC.film_id
JOIN category C 
ON C.category_id = FC.category_id
GROUP BY C.category_id , C.name;

#Bonus:
#5 Identify the film categories with the longest average running time.  
select C.name, AVG(F.length) AS average_running_time
from film F
JOIN film_category FC
ON F.film_id = FC.film_id
JOIN category C 
ON C.category_id = FC.category_id 
GROUP BY C.name
ORDER BY average_running_time DESC;

